### ISSUE TITLE
Habit-Tracker

### ISSUE THREAD

**Issue by derfelix42** [derfelix42/Taskmanager#3]
Create a habit tracker to track habits on a daily, weekly, monthly basis

**Comment by derfelix42** [comment]
Needs to be refined. Current problems / ideas:
- Group habits (like Morningroutine containing showering, ect...)
- Add / Remove habits
- Auto check habits based on done tasks (sports / morningroutine)
-

**Comment by derfelix42** [comment]
Mobile Optimization

**Comment by derfelix42** [comment]
Open Todos for 1.1 release:
- [ ] improve design on going through months
- [ ] fix year wrap
- [ ] design "add new group"
- [ ] delete group
- [ ] rename group

**Comment by derfelix42** [comment]
Closed via 612e474d2faae6d13bc60d5e5bf6e5a04f0ab334
